# Generated by Django 4.2.8 on 2023-12-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('pronouns', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('birth_location', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('connection', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_home', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_work', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('employer', models.CharField(blank=True, max_length=100, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_since', models.DateField(blank=True, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('relationship_status', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('kids_number', models.PositiveIntegerField(blank=True, null=True)),
                ('children_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
