# Generated by Django 5.0 on 2023-12-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('insurances', '0002_rename_insurancecompany_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='insurances',
            field=models.ManyToManyField(to='insurances.insurance'),
        ),
    ]
