# Generated by Django 5.0 on 2023-12-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_insurances'),
        ('insurances', '0002_rename_insurancecompany_insurance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='client',
            name='insurances',
            field=models.ManyToManyField(to='insurances.insurance', verbose_name='Insurances'),
        ),
    ]
