# Generated by Django 5.0 on 2023-12-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_options_alter_client_insurances'),
        ('insurances', '0002_rename_insurancecompany_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='insurances',
            field=models.ManyToManyField(null=True, to='insurances.insurance', verbose_name='Insurances'),
        ),
    ]
