# Generated by Django 4.2.8 on 2023-12-16 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_clients_tracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
